app:
  log:
    fileName: "app-log"
    filePath: "server/logs"
  debug: true
  host: 127.0.0.1
  name: netGame
  version: 1.0.
  listenPoints: 8080
  MaxConn: 1000
  MaxPackageSize: 4096
  WorkerPoolSize: 10
  MaxWorkerTaskLen: 1024






